FROM eclipse-temurin:25-jdk AS build

WORKDIR /app

COPY . .

RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre AS deploy

WORKDIR /app

COPY --from=build /app/target/classes/com/esi/ms-remboursement.jar .

CMD ["java","-jar","ms-remboursement.jar"]
