FROM eclipse-temurin:21-jdk AS build

WORKDIR /app

COPY . .

RUN ./mvnw clean compile

RUN ./mvnw clean package -DskipTests


FROM eclipse-temurin:21-jre AS deploy

COPY --from=build /app/target/ms-remboursement.jar .

CMD = ["java","-jar","ms-remboursement.jar"]
